//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2300
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2300.
// 
namespace Orbit.OrbitServices.OrbitServicesHost {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OrbitServicesSoap", Namespace="http://tempuri.org/")]
    public class OrbitServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public OrbitServices() {
            this.Url = "http://orbitservices.menge.mine.nu/orbitservices.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportError", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ReportError(string ErrorInformation) {
            object[] results = this.Invoke("ReportError", new object[] {
                        ErrorInformation});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReportError(string ErrorInformation, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReportError", new object[] {
                        ErrorInformation}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndReportError(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportErrorWithInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ReportErrorWithInfo(string ErrorInformation, string UserInformation) {
            object[] results = this.Invoke("ReportErrorWithInfo", new object[] {
                        ErrorInformation,
                        UserInformation});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReportErrorWithInfo(string ErrorInformation, string UserInformation, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReportErrorWithInfo", new object[] {
                        ErrorInformation,
                        UserInformation}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndReportErrorWithInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WasReported", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WasReported(string ErrorInformation) {
            object[] results = this.Invoke("WasReported", new object[] {
                        ErrorInformation});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWasReported(string ErrorInformation, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WasReported", new object[] {
                        ErrorInformation}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndWasReported(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLatestVersionNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Single GetLatestVersionNumber() {
            object[] results = this.Invoke("GetLatestVersionNumber", new object[0]);
            return ((System.Single)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLatestVersionNumber(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLatestVersionNumber", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Single EndGetLatestVersionNumber(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Single)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHomepageAddress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHomepageAddress() {
            object[] results = this.Invoke("GetHomepageAddress", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetHomepageAddress(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetHomepageAddress", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetHomepageAddress(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
